version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: graph-nginx
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - graph_logs:/var/log/nginx
    environment:
      - TZ=Europe/Kiev
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.graph.rule=Host(`graph.perek.rest`)"
      - "traefik.http.routers.graph.entrypoints=websecure"
      - "traefik.http.routers.graph.tls=true"
      - "traefik.http.routers.graph.tls.certresolver=myresolver"
      - "traefik.http.services.graph.loadbalancer.server.port=80"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  graph_logs:

networks:
  web-network:
    external: true