version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: graph-nginx
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - graph_logs:/var/log/nginx
    environment:
      - TZ=Europe/Kiev
      # Дополнительные переменные окружения можно добавить здесь
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  graph_logs:
